### ISSUE TITLE
Crash generating a new Crypter when matadata contains password.

### ISSUE THREAD

**Issue by P82maarj** [jbtule/keyczar-dotnet#12]
Maybe I'm doing something wrong.
If:
1. KeyczarTool.exe create --location=[path] --purpose=crypt
2. KeyczarTool.exe create --location=[path] --status=primary 
3. Crypter cyp = new Crypter(path);
All ok.
If:
1. KeyczarTool.exe create --location=[path] --purpose=crypt
2. KeyczarTool.exe create --location=[path] --status=primary **--password**
3. Crypter cyp = new Crypter(path); <--Crash

Should I do something if metadata contains a password for avoiding the crash?
Thanks for your project and Regards,

**Comment by jbtule** [comment]
```csharp
PbeKeySet pks= PbeKeySet(path, FunctionOrLambdaThatReturnsPassword);
Crypter cyp = new Crypter(pks); 
```
