### ISSUE TITLE
Fix Travis-CI

### ISSUE THREAD

**Issue by jbtule** [jbtule/keyczar-dotnet#5]

**Comment by BryanAvery** [comment]
What is the problem with this and what is required to be done?

**Comment by jbtule** [comment]
Travis-CI builds and run unit tests on pull-requests. Right now it's failing, but not because of an issue with the code, but because of the build config https://travis-ci.org/jbtule/keyczar-dotnet.  The current config isn't working, says mono doesn't exist. This is likely because it uses an old config not meant technically meant for c# and something has changes on travis-ci.  However, there is documentation now for an official csharp language config.  https://docs.travis-ci.com/user/languages/csharp/ and so the .travis.yml needs to be updated to fit with this new config.
